<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Contensive.Addons.ThemeHelpers</RootNamespace>
    <AssemblyName>ThemeHelpers</AssemblyName>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Contensive.CPBaseClass" Version="26.9.25.22751" />
    <PackageReference Include="Contensive.DbModels" Version="26.9.25.22751" />
  </ItemGroup>
</Project>
